name: build-container

on:
  push:
    branches:
    - main
    tags:        
      - v*
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/dergeberl/kubeteach-webterminal,dergeberl/kubeteach-webterminal
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      if: ${{ github.event_name != 'pull_request' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      if: ${{ github.event_name != 'pull_request' }}
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}